"""Brandfetch course diagrams as inline SVG (GRS-0225). GENERATED — DO NOT EDIT.

Regenerate with `uv run python design/motion/svg_export.py`. The source is the SceneSpec JSON under
`design/motion/courses/brandfetch/`; edit that, not this. `tests/test_course_diagrams.py` fails if
this file and those scenes disagree.

Captions and alt text are NOT here: they are authored prose and live beside the slide they explain,
in `brandfetch_slides.py`. Only the drawing is generated.
"""

from __future__ import annotations

SVG: dict[str, str] = {
    "four_surfaces": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 470" width="960" height="470">'
        '<g transform="translate(480,235)"><rect x="-480" y="-235" width="960" height="470" fill="#F7F5EF"/></g>'
        '<text x="480" y="430" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Demo the free surface. Sell the paid one. They are not the same conversation.</text>'
        '<g transform="translate(480,372)"><rect x="-430" y="-1" width="860" height="2" fill="#1A1A18"/></g>'
        '<g transform="translate(810,267)"><rect x="-98" y="-105" width="196" height="210" rx="14" fill="#1A3B26"/></g>'
        '<text x="810" y="398" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">enterprise</text>'
        '<text x="810" y="218" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">messy descriptors</text>'
        '<text x="810" y="192" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Transaction API</text>'
        '<g transform="translate(590,292)"><rect x="-98" y="-80" width="196" height="160" rx="14" fill="#1A3B26"/></g>'
        '<text x="590" y="398" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">paid</text>'
        '<text x="590" y="268" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">identity by ticker</text>'
        '<text x="590" y="242" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Brand API</text>'
        '<g transform="translate(370,317)"><rect x="-98" y="-55" width="196" height="110" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="370" y="398" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">free tier</text>'
        '<text x="370" y="318" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">a type-ahead</text>'
        '<text x="370" y="292" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Brand Search</text>'
        '<g transform="translate(150,337)"><rect x="-98" y="-35" width="196" height="70" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="150" y="398" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">free tier</text>'
        '<text x="150" y="358" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">an image URL</text>'
        '<text x="150" y="332" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Logo Link</text>'
        '<text x="480" y="78" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Height is commitment, not price.</text>'
        '<text x="480" y="44" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Land free, expand into the paid data</text>'
        "</svg>"
    ),
    "holdings_before_after": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 420" width="960" height="420">'
        '<g transform="translate(480,210)"><rect x="-480" y="-210" width="960" height="420" fill="#F7F5EF"/></g>'
        '<text x="480" y="382" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">One image URL keyed on the ticker. This is the whole retail demo.</text>'
        '<g transform="translate(700,216)"><rect x="-170" y="-108" width="340" height="216" rx="14" fill="#E4EBE5" stroke="#1A3B26" stroke-width="2"/></g>'
        '<g transform="translate(250,216)"><rect x="-170" y="-108" width="340" height="216" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="700" y="314" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">scannable in one look</text>'
        '<text x="250" y="314" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">a wall of symbols</text>'
        '<text x="700" y="260" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">VOD.L</text>'
        '<g transform="translate(640,260)"><rect x="-11" y="-11" width="22" height="22" rx="5" fill="#1A3B26"/></g>'
        '<text x="250" y="260" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">VOD.L</text>'
        '<text x="700" y="216" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">MSFT</text>'
        '<g transform="translate(640,216)"><rect x="-11" y="-11" width="22" height="22" rx="5" fill="#1A3B26"/></g>'
        '<text x="250" y="216" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">MSFT</text>'
        '<text x="700" y="172" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">NKE</text>'
        '<g transform="translate(640,172)"><rect x="-11" y="-11" width="22" height="22" rx="5" fill="#1A3B26"/></g>'
        '<text x="250" y="172" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">NKE</text>'
        '<text x="700" y="118" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="12" letter-spacing="1.6" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">WITH</text>'
        '<text x="250" y="118" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="12" letter-spacing="1.6" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">WITHOUT</text>'
        '<text x="480" y="44" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">The same holdings table</text>'
        "</svg>"
    ),
    "qualify_before_you_forecast": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 420" width="1000" height="420">'
        '<g transform="translate(500,210)"><rect x="-500" y="-210" width="1000" height="420" fill="#F7F5EF"/></g>'
        '<text x="500" y="390" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Never from memory, and never from a slide: the schedule is the only source.</text>'
        '<text x="500" y="348" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">Different rate, different window. Read yours off the Earnings page.</text>'
        '<g transform="translate(730,176)"><rect x="-1.25" y="-13.5" width="2.5" height="27" fill="#6E6A60"/></g>'
        '<g transform="translate(730,194) rotate(180)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(270,176)"><rect x="-1.25" y="-13.5" width="2.5" height="27" fill="#6E6A60"/></g>'
        '<g transform="translate(270,194) rotate(180)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(730,262)"><rect x="-150" y="-50" width="300" height="100" rx="14" fill="#1A3B26"/></g>'
        '<g transform="translate(270,262)"><rect x="-150" y="-50" width="300" height="100" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="730" y="278" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">enterprise licensing</text>'
        '<text x="730" y="246" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Redistribution</text>'
        '<text x="270" y="278" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">standard paid API</text>'
        '<text x="270" y="246" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Distribution</text>'
        '<text x="700" y="186" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Yes</text>'
        '<text x="300" y="186" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">No</text>'
        '<g transform="translate(500,130)"><rect x="-280" y="-29" width="560" height="58" rx="14" fill="#F7F5EF" stroke="#1A1A18" stroke-width="2"/></g>'
        '<text x="500" y="130" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="21" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Does the data leave the client\'s own product?</text>'
        '<text x="500" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Qualify the licence before you forecast</text>'
        "</svg>"
    ),
    "reference_data_shelf": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 980 440" width="980" height="440">'
        '<g transform="translate(490,220)"><rect x="-490" y="-220" width="980" height="440" fill="#F7F5EF"/></g>'
        '<text x="490" y="398" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#A3502A" text-anchor="middle" dominant-baseline="central">That arrow is the licence question. It is why this tier exists.</text>'
        '<g transform="translate(800,225)"><rect x="-130" y="-80" width="260" height="160" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="800" y="264" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">their building</text>'
        '<text x="800" y="240" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">the data leaves</text>'
        '<text x="800" y="200" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Their customers</text>'
        '<g transform="translate(560,225)"><rect x="-60.5" y="-1.25" width="121" height="2.5" fill="#1A3B26"/></g>'
        '<g transform="translate(625,225) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#1A3B26"/></g>'
        '<g transform="translate(250,225)"><rect x="-180" y="-110" width="360" height="220" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(250,282)"><rect x="-160" y="-16" width="320" height="32" rx="6" fill="#1A3B26"/></g>'
        '<text x="250" y="282" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">brand identity</text>'
        '<text x="250" y="244" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">SEDOL, MIC, currency</text>'
        '<text x="250" y="206" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">legal name</text>'
        '<text x="250" y="168" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">ISIN</text>'
        '<text x="250" y="128" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="11" letter-spacing="1.2" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">THEIR REFERENCE RECORD</text>'
        '<text x="490" y="78" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">An exchange or vendor redistributes reference data every day.</text>'
        '<text x="490" y="44" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">One more field on a record they already ship</text>'
        "</svg>"
    ),
    "the_ticker_hook": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 500" width="1000" height="500">'
        '<g transform="translate(500,250)"><rect x="-500" y="-250" width="1000" height="500" fill="#F7F5EF"/></g>'
        '<text x="500" y="452" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">A generic logo API takes a domain. That is the wrong key for a holdings table.</text>'
        '<g transform="translate(745,259)"><rect x="-165" y="-75" width="330" height="150" rx="14" fill="#1A3B26"/></g>'
        '<text x="745" y="296" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">firmographics</text>'
        '<text x="745" y="272" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">colours and fonts</text>'
        '<text x="745" y="248" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">logo in every variant</text>'
        '<text x="745" y="210" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="20" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">One brand identity</text>'
        '<g transform="translate(425,370)"><rect x="-40.5" y="-1.25" width="81" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(470,370) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(190,370)"><rect x="-150" y="-31" width="300" height="62" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="190" y="382" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">BTC</text>'
        '<text x="190" y="360" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">a crypto symbol</text>'
        '<g transform="translate(425,296)"><rect x="-40.5" y="-1.25" width="81" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(470,296) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(190,296)"><rect x="-150" y="-31" width="300" height="62" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="190" y="308" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">US6541061031</text>'
        '<text x="190" y="286" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">an ISIN</text>'
        '<g transform="translate(425,222)"><rect x="-40.5" y="-1.25" width="81" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(470,222) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(190,222)"><rect x="-150" y="-31" width="300" height="62" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="190" y="234" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">NKE</text>'
        '<text x="190" y="212" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">a stock ticker</text>'
        '<g transform="translate(425,148)"><rect x="-40.5" y="-1.25" width="81" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(470,148) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(190,148)"><rect x="-150" y="-31" width="300" height="62" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="190" y="160" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="13" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">nike.com</text>'
        '<text x="190" y="138" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">a domain</text>'
        '<text x="500" y="78" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Your client\'s records are keyed by ticker or ISIN, not by domain.</text>'
        '<text x="500" y="44" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Four keys, one endpoint</text>'
        "</svg>"
    ),
    "two_licences": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1180 500" width="1180" height="500">'
        '<g transform="translate(590,250)"><rect x="-590" y="-250" width="1180" height="500" fill="#F7F5EF"/></g>'
        '<text x="660" y="462" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#A3502A" text-anchor="middle" dominant-baseline="central">The line is not publicly bright-lined. Never decide it yourself.</text>'
        '<g transform="translate(660,288)"><rect x="-1" y="-150" width="2" height="300" fill="#1A1A18"/></g>'
        '<g transform="translate(420,288)"><rect x="-210" y="-130" width="420" height="260" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(900,288)"><rect x="-210" y="-130" width="420" height="260" rx="14" fill="#1A3B26"/></g>'
        '<text x="108" y="366" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="11" letter-spacing="1.2" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">WHO BUYS IT</text>'
        '<text x="108" y="288" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="11" letter-spacing="1.2" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">WHAT LICENCE</text>'
        '<text x="108" y="210" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="11" letter-spacing="1.2" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">WHERE THE DATA GOES</text>'
        '<text x="900" y="377" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">information vendors</text>'
        '<text x="900" y="355" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Exchanges and</text>'
        '<text x="420" y="355" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Retail brokerages</text>'
        '<text x="900" y="299" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">licensing only</text>'
        '<text x="900" y="277" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Enterprise custom</text>'
        '<text x="420" y="299" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">self-serve</text>'
        '<text x="420" y="277" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Standard paid API,</text>'
        '<text x="900" y="221" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">customers</text>'
        '<text x="900" y="199" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Passed on to their</text>'
        '<text x="420" y="221" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">own product</text>'
        '<text x="420" y="199" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Shown inside their</text>'
        '<text x="900" y="138" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" letter-spacing="1.4" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">REDISTRIBUTION</text>'
        '<text x="420" y="138" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" letter-spacing="1.4" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">DISTRIBUTION</text>'
        '<text x="660" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">One boundary decides the whole deal</text>'
        "</svg>"
    ),
    "two_sides": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 440" width="960" height="440">'
        '<g transform="translate(480,220)"><rect x="-480" y="-220" width="960" height="440" fill="#F7F5EF"/></g>'
        '<text x="480" y="398" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">A scraper has no one maintaining it. That is the whole argument.</text>'
        '<g transform="translate(730,240)"><rect x="-190" y="-100" width="380" height="200" rx="14" fill="#1A3B26"/></g>'
        '<g transform="translate(230,240)"><rect x="-190" y="-100" width="380" height="200" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(480,240)"><rect x="-55.5" y="-1.25" width="111" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(540,240) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<text x="730" y="274" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#7FD4A0" text-anchor="middle" dominant-baseline="central">this is what you sell</text>'
        '<text x="730" y="234" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">brand identity out</text>'
        '<text x="730" y="210" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">one identifier in,</text>'
        '<text x="730" y="168" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="21" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">The developer API</text>'
        '<text x="230" y="298" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">firmographics</text>'
        '<text x="230" y="274" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">logos, colours, fonts,</text>'
        '<text x="230" y="234" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">profile and verifies it</text>'
        '<text x="230" y="210" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">a company claims its own</text>'
        '<text x="230" y="168" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="21" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">The public registry</text>'
        '<text x="480" y="80" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">The brands maintain it. That is why the data is current.</text>'
        '<text x="480" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">One registry, two sides</text>'
        "</svg>"
    ),
    "who_owns_the_mark": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 440" width="1000" height="440">'
        '<g transform="translate(500,220)"><rect x="-500" y="-220" width="1000" height="440" fill="#F7F5EF"/></g>'
        '<text x="500" y="396" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Say this before the compliance officer asks. It stays a short conversation.</text>'
        '<text x="500" y="348" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#A3502A" text-anchor="middle" dominant-baseline="central">Paying for access does not transfer anybody\'s rights.</text>'
        '<g transform="translate(820,212)"><rect x="-130" y="-85" width="260" height="170" rx="14" fill="#1A3B26"/></g>'
        '<g transform="translate(500,212)"><rect x="-130" y="-85" width="260" height="170" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(180,212)"><rect x="-130" y="-85" width="260" height="170" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(660,212)"><rect x="-45.5" y="-1.25" width="91" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(710,212) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(340,212)"><rect x="-45.5" y="-1.25" width="91" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(390,212) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<text x="820" y="248" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">fair-use risk</text>'
        '<text x="820" y="224" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">carries the</text>'
        '<text x="820" y="178" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Your client</text>'
        '<text x="500" y="248" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">to it</text>'
        '<text x="500" y="224" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">provides access</text>'
        '<text x="500" y="178" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Brandfetch</text>'
        '<text x="180" y="246" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">owns the mark</text>'
        '<text x="180" y="202" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">owner</text>'
        '<text x="180" y="178" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">The trademark</text>'
        '<text x="500" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Three parties, and the risk is not where they think</text>'
        "</svg>"
    ),
}
