"""The Sales Egoist course diagrams as inline SVG (GRS-0225). GENERATED — DO NOT EDIT.

Regenerate with `uv run python design/motion/svg_export.py`. The source is the SceneSpec JSON under
`design/motion/courses/sales_egoist/`; edit that, not this. `tests/test_course_diagrams.py` fails if
this file and those scenes disagree.

Captions and alt text are NOT here: they are authored prose and live beside the slide they explain,
in `sales_egoist_slides.py`. Only the drawing is generated.
"""

from __future__ import annotations

SVG: dict[str, str] = {
    "placeholder_or_principal": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 600" width="1120" height="600">'
        '<g transform="translate(560,300)"><rect x="-560" y="-300" width="1120" height="600" fill="#F7F5EF"/></g>'
        '<g transform="translate(820,324)"><rect x="-230" y="-165" width="460" height="330" rx="14" fill="#1A3B26"/></g>'
        '<g transform="translate(300,324)"><rect x="-230" y="-165" width="460" height="330" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="560" y="548" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">A seller who waits becomes a placeholder. Interchangeable, and easily replaced.</text>'
        '<text x="820" y="452" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Is irreplaceable</text>'
        '<text x="300" y="452" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Is interchangeable</text>'
        '<text x="820" y="388" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Sets the timeline</text>'
        '<text x="300" y="388" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Moves on the buyer\'s timeline</text>'
        '<text x="820" y="324" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Reports territory taken</text>'
        '<text x="300" y="324" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Reports activity</text>'
        '<text x="820" y="260" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Turns trust into real leverage</text>'
        '<text x="300" y="260" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Hopes relationships mature</text>'
        '<text x="820" y="196" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">Engineers the reason to engage</text>'
        '<text x="300" y="196" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Waits for inbound and RFPs</text>'
        '<text x="820" y="122" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" letter-spacing="1.5" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">THE PRINCIPAL</text>'
        '<text x="300" y="122" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" letter-spacing="1.5" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">THE PLACEHOLDER</text>'
        '<text x="560" y="48" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="28" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">The same five situations, answered two ways</text>'
        "</svg>"
    ),
    "the_armoury": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 560" width="1120" height="560">'
        '<g transform="translate(560,280)"><rect x="-560" y="-280" width="1120" height="560" fill="#F7F5EF"/></g>'
        '<g transform="translate(860,440)"><rect x="-136" y="-88" width="272" height="176" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(560,440)"><rect x="-136" y="-88" width="272" height="176" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(260,440)"><rect x="-136" y="-88" width="272" height="176" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(860,220)"><rect x="-136" y="-88" width="272" height="176" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(560,220)"><rect x="-136" y="-88" width="272" height="176" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(260,220)"><rect x="-136" y="-88" width="272" height="176" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="860" y="490" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">The Timing Layer</text>'
        '<text x="860" y="464" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Social and Digital</text>'
        '<text x="860" y="424" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">and presence</text>'
        '<text x="860" y="396" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Timing</text>'
        '<text x="560" y="490" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Target Account Selling</text>'
        '<text x="560" y="464" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Miller Heiman Blue Sheet</text>'
        '<text x="560" y="424" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">and account</text>'
        '<text x="560" y="396" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Committee</text>'
        '<text x="260" y="490" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Sandler . NEAT / SNAP</text>'
        '<text x="260" y="464" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">MEDDIC / MEDDPICC</text>'
        '<text x="260" y="424" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">and deal control</text>'
        '<text x="260" y="396" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Qualification</text>'
        '<text x="860" y="270" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Mutual Action Plan</text>'
        '<text x="860" y="244" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Value / ROI Selling</text>'
        '<text x="860" y="204" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">and economics</text>'
        '<text x="860" y="176" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Value</text>'
        '<text x="560" y="270" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Command of the Message</text>'
        '<text x="560" y="244" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Challenger . Provocation</text>'
        '<text x="560" y="204" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">and reframing</text>'
        '<text x="560" y="176" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Insight</text>'
        '<text x="260" y="270" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Conceptual . Gap</text>'
        '<text x="260" y="244" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">SPIN . Solution</text>'
        '<text x="260" y="204" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">and diagnosis</text>'
        '<text x="260" y="176" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Discovery</text>'
        '<text x="560" y="84" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Wide on purpose: not so you use everything, so you choose with knowledge.</text>'
        '<text x="560" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="27" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">The armoury, organised by what you need it to do</text>'
        "</svg>"
    ),
    "the_battlefield": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 500" width="1120" height="500">'
        '<g transform="translate(560,250)"><rect x="-560" y="-250" width="1120" height="500" fill="#F7F5EF"/></g>'
        '<text x="560" y="448" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">The incumbent outage in a bursty session. Position as though it is a when.</text>'
        '<text x="560" y="410" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" letter-spacing="1.4" fill="#A3502A" text-anchor="middle" dominant-baseline="central">UNDATED, AND INEVITABLE</text>'
        '<g transform="translate(560,320)"><rect x="-450" y="-1.5" width="900" height="3" fill="#D8D3C7"/></g>'
        '<g transform="translate(930,320)"><rect x="-8" y="-8" width="16" height="16" rx="8" fill="#1A3B26"/></g>'
        '<text x="930" y="294" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">move to T+1</text>'
        '<text x="930" y="268" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">UK, EU and Switzerland</text>'
        '<text x="930" y="214" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">11 Oct 2027</text>'
        '<g transform="translate(630,320)"><rect x="-8" y="-8" width="16" height="16" rx="8" fill="#1A3B26"/></g>'
        '<text x="630" y="294" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">confirmations mandated</text>'
        '<text x="630" y="268" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">T+0 allocations and</text>'
        '<text x="630" y="214" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">Dec 2026</text>'
        '<g transform="translate(390,320)"><rect x="-8" y="-8" width="16" height="16" rx="8" fill="#1A1A18"/></g>'
        '<text x="390" y="294" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">begin to bite</text>'
        '<text x="390" y="268" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">EU AI Act obligations</text>'
        '<text x="390" y="214" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Aug 2026</text>'
        '<g transform="translate(150,320)"><rect x="-8" y="-8" width="16" height="16" rx="8" fill="#6E6A60"/></g>'
        '<text x="150" y="268" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">US moves to T+1</text>'
        '<text x="150" y="214" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="18" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">May 2024</text>'
        '<text x="560" y="84" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Budgets thaw when a board-level deadline forces them to.</text>'
        '<text x="560" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="27" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">The dated catalysts an egoist works backwards from</text>'
        "</svg>"
    ),
    "the_campaign": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1400 500" width="1400" height="500">'
        '<g transform="translate(700,250)"><rect x="-700" y="-250" width="1400" height="500" fill="#F7F5EF"/></g>'
        '<text x="700" y="462" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">That is the Bruntsfield playbook: a closed loop from conviction to ownership.</text>'
        '<g transform="translate(1240,224)"><rect x="-150" y="-84" width="300" height="168" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(890,224)"><rect x="-150" y="-84" width="300" height="168" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(540,224)"><rect x="-150" y="-84" width="300" height="168" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(190,224)"><rect x="-150" y="-84" width="300" height="168" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(700,394)"><rect x="-600" y="-27" width="1200" height="54" rx="14" fill="#1A3B26"/></g>'
        '<text x="700" y="394" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" letter-spacing="1.3" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">VIII . TOTAL ACCOUNT AWARENESS RUNS THE WHOLE WAY THROUGH</text>'
        '<g transform="translate(1048,224)"><rect x="-11.5" y="-1.25" width="23" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(1064,224) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(698,224)"><rect x="-11.5" y="-1.25" width="23" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(714,224) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(348,224)"><rect x="-11.5" y="-1.25" width="23" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(364,224) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<text x="1240" y="252" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">before an RFP exists</text>'
        '<text x="1240" y="226" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Pre-emptive strike (VIII)</text>'
        '<text x="1240" y="172" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" letter-spacing="1.3" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">THE CLOSE</text>'
        '<text x="890" y="252" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Drop the script (VII)</text>'
        '<text x="890" y="226" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Orchestrate the committee (V)</text>'
        '<text x="890" y="172" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" letter-spacing="1.3" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">THE ENGAGEMENT</text>'
        '<text x="540" y="252" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Seek the hardest room (IV)</text>'
        '<text x="540" y="226" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Run the documented play (III)</text>'
        '<text x="540" y="172" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" letter-spacing="1.3" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">THE TRIGGER</text>'
        '<text x="190" y="278" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Be present early (VI)</text>'
        '<text x="190" y="252" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Enter with one weapon (II)</text>'
        '<text x="190" y="226" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Choose the hard account (I)</text>'
        '<text x="190" y="172" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" letter-spacing="1.3" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">BEFORE</text>'
        '<text x="700" y="84" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">They are not eight skills practised apart. Run end to end they look like this.</text>'
        '<text x="700" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="28" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Eight convictions, one campaign</text>'
        "</svg>"
    ),
    "the_committee": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 580" width="1120" height="580">'
        '<g transform="translate(560,290)"><rect x="-560" y="-290" width="1120" height="580" fill="#F7F5EF"/></g>'
        '<g transform="translate(880,322)"><rect x="-150" y="-210" width="300" height="420" rx="14" fill="#E4EBE5"/></g>'
        '<g transform="translate(560,468)"><rect x="-450" y="-0.5" width="900" height="1" fill="#D8D3C7"/></g>'
        '<text x="880" y="498" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">Mutual action plan</text>'
        '<text x="560" y="498" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">wants price and terms</text>'
        '<text x="240" y="498" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Procurement</text>'
        '<g transform="translate(560,410)"><rect x="-450" y="-0.5" width="900" height="1" fill="#D8D3C7"/></g>'
        '<text x="880" y="440" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">Governance narrative</text>'
        '<text x="560" y="440" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">wants explainability</text>'
        '<text x="240" y="440" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Compliance</text>'
        '<g transform="translate(560,352)"><rect x="-450" y="-0.5" width="900" height="1" fill="#D8D3C7"/></g>'
        '<text x="880" y="382" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">Trust plus regulatory case</text>'
        '<text x="560" y="382" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">wants real-time risk</text>'
        '<text x="240" y="382" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">The CRO</text>'
        '<g transform="translate(560,294)"><rect x="-450" y="-0.5" width="900" height="1" fill="#D8D3C7"/></g>'
        '<text x="880" y="324" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">Strangler-gateway story</text>'
        '<text x="560" y="324" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">wants resilience, no lock-in</text>'
        '<text x="240" y="324" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Head of Architecture</text>'
        '<g transform="translate(560,236)"><rect x="-450" y="-0.5" width="900" height="1" fill="#D8D3C7"/></g>'
        '<text x="880" y="266" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">A working demo</text>'
        '<text x="560" y="266" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">wants elegant data access</text>'
        '<text x="240" y="266" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">The quant</text>'
        '<text x="880" y="208" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">Challenger insight</text>'
        '<text x="560" y="208" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">wants speed</text>'
        '<text x="240" y="208" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="17" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Head of Trading</text>'
        '<text x="880" y="146" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" letter-spacing="1.4" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">WHAT MOVES THEM</text>'
        '<text x="560" y="146" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" letter-spacing="1.4" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">WHAT THEY WANT</text>'
        '<text x="240" y="146" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" letter-spacing="1.4" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">THE SEAT</text>'
        '<text x="560" y="84" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">No single message satisfies all of them. The wrong weapon is a disqualification.</text>'
        '<text x="560" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="27" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">One committee, six appetites, six weapons</text>'
        "</svg>"
    ),
    "the_deal_equation": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 600" width="1120" height="600">'
        '<g transform="translate(560,300)"><rect x="-560" y="-300" width="1120" height="600" fill="#F7F5EF"/></g>'
        '<text x="560" y="530" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">Doubling your reach rate does as much as doubling your win rate.</text>'
        '<g transform="translate(560,424)"><rect x="-310" y="-48" width="620" height="96" rx="14" fill="#F7F5EF" stroke="#A3502A" stroke-width="2"/></g>'
        '<text x="560" y="448" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Millions in cost, contracts in years. Absorb it and you have raised the odds.</text>'
        '<text x="560" y="412" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#A3502A" text-anchor="middle" dominant-baseline="central">The incumbent\'s switching cost</text>'
        '<text x="560" y="356" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" letter-spacing="1.4" fill="#A3502A" text-anchor="middle" dominant-baseline="central">LOWERS IT</text>'
        '<g transform="translate(920,240)"><rect x="-82" y="-66" width="164" height="132" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="920" y="278" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">the committee</text>'
        '<text x="920" y="254" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">agreement across</text>'
        '<text x="920" y="216" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Consensus</text>'
        '<g transform="translate(740,240)"><rect x="-82" y="-66" width="164" height="132" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="740" y="278" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">you can show</text>'
        '<text x="740" y="254" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">fidelity of what</text>'
        '<text x="740" y="216" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Proof</text>'
        '<g transform="translate(560,240)"><rect x="-82" y="-66" width="164" height="132" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="560" y="278" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">your thesis</text>'
        '<text x="560" y="254" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">differentiation of</text>'
        '<text x="560" y="216" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Insight</text>'
        '<g transform="translate(380,240)"><rect x="-82" y="-66" width="164" height="132" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="380" y="278" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">economic buyer</text>'
        '<text x="380" y="254" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">access to the</text>'
        '<text x="380" y="216" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Reach</text>'
        '<g transform="translate(200,240)"><rect x="-82" y="-66" width="164" height="132" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<text x="200" y="278" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">you are riding</text>'
        '<text x="200" y="254" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">the dated catalyst</text>'
        '<text x="200" y="216" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Trigger</text>'
        '<text x="560" y="140" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" letter-spacing="1.4" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">RAISES WIN PROBABILITY</text>'
        '<text x="560" y="84" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Every variable is a lever, not a given. Diagnose which term is dragging.</text>'
        '<text x="560" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="27" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Win probability is five levers and one drag</text>'
        "</svg>"
    ),
    "the_flow_channel": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1400 660" width="1400" height="660">'
        '<g transform="translate(700,330)"><rect x="-700" y="-330" width="1400" height="660" fill="#F7F5EF"/></g>'
        '<g transform="translate(720,350)"><rect x="-540" y="-210" width="1080" height="420" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(720,380)"><rect x="-170" y="-65" width="340" height="130" rx="14" fill="#E4EBE5"/></g>'
        '<text x="1046" y="520" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">to your best seller.</text>'
        '<text x="1046" y="496" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">The trivial renewal given</text>'
        '<text x="1046" y="458" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="20" letter-spacing="1.4" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">BOREDOM</text>'
        '<text x="720" y="412" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">with one demanding goal.</text>'
        '<text x="720" y="388" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Difficulty matched to the seller,</text>'
        '<text x="720" y="352" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="22" letter-spacing="1.6" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">FLOW</text>'
        '<text x="396" y="292" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Fear drives over-discounting.</text>'
        '<text x="396" y="268" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">you sent a junior into.</text>'
        '<text x="396" y="244" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">The Tier-1 procurement battle</text>'
        '<text x="396" y="206" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="20" letter-spacing="1.4" fill="#A3502A" text-anchor="middle" dominant-baseline="central">ANXIETY</text>'
        '<text x="720" y="596" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" letter-spacing="1.4" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">SKILL</text>'
        '<text x="96" y="350" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" letter-spacing="1.4" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">CHALLENGE</text>'
        '<text x="700" y="84" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">Peak performance sits where challenge meets skill. It is engineered, not awaited.</text>'
        '<text x="700" y="46" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="27" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">Boredom, flow, anxiety: calibrate the room</text>'
        "</svg>"
    ),
    "tool_to_weapon": (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 500" width="1120" height="500">'
        '<g transform="translate(560,250)"><rect x="-560" y="-250" width="1120" height="500" fill="#F7F5EF"/></g>'
        '<g transform="translate(890,250)"><rect x="-130" y="-95" width="260" height="190" rx="14" fill="#1A3B26"/></g>'
        '<g transform="translate(560,250)"><rect x="-130" y="-95" width="260" height="190" rx="14" fill="#E4EBE5" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(230,250)"><rect x="-130" y="-95" width="260" height="190" rx="14" fill="#F7F5EF" stroke="#D8D3C7" stroke-width="2"/></g>'
        '<g transform="translate(702,240)"><rect x="-18.5" y="-1.25" width="37" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(725,240) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<g transform="translate(372,240)"><rect x="-18.5" y="-1.25" width="37" height="2.5" fill="#6E6A60"/></g>'
        '<g transform="translate(395,240) rotate(90)"><polygon points="0,-7.2 7.2,7.2 -7.2,7.2" fill="#6E6A60"/></g>'
        '<text x="560" y="456" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="14" letter-spacing="1.4" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">A FORMULA, NOT A FEATURE LIST</text>'
        '<text x="560" y="416" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="19" fill="#1A3B26" text-anchor="middle" dominant-baseline="central">When I do X to buyer Y, I produce outcome Z.</text>'
        '<text x="890" y="296" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">when and how it wins.</text>'
        '<text x="890" y="272" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">The repeatable equation for</text>'
        '<text x="890" y="224" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="22" letter-spacing="1.6" fill="#EDF2EE" text-anchor="middle" dominant-baseline="central">FORMULA</text>'
        '<text x="890" y="178" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#B9C7BC" text-anchor="middle" dominant-baseline="central">03</text>'
        '<text x="560" y="296" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">deliberately as your one edge.</text>'
        '<text x="560" y="272" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">That tool, chosen</text>'
        '<text x="560" y="224" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="22" letter-spacing="1.6" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">WEAPON</text>'
        '<text x="560" y="178" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">02</text>'
        '<text x="230" y="296" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">happen to know.</text>'
        '<text x="230" y="272" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">A methodology you</text>'
        '<text x="230" y="224" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="22" letter-spacing="1.6" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">TOOL</text>'
        '<text x="230" y="178" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="15" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">01</text>'
        '<text x="560" y="88" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="16" fill="#6E6A60" text-anchor="middle" dominant-baseline="central">A method becomes a weapon only when you define the formula for how it strikes.</text>'
        '<text x="560" y="48" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="30" fill="#1A1A18" text-anchor="middle" dominant-baseline="central">A tool is not a weapon</text>'
        "</svg>"
    ),
}
